schema_version = "1.0.0"

id = "render_manager"
version = "1.0.0"
name = "Render Manager"
tagline = "Submit render jobs to Render Manager"
maintainer = "Tobias Rossi"
type = "add-on"
license = ["SPDX:GPL-3.0-or-later"]
blender_version_min = "4.2.0"
